# Налаштування сайту
title: "Думки та нотатки"
author: "Roman Kozak"
description: "Особистий блог про життя, ідеї та все, що не стосується коду."

# URL та baseurl (ВАЖЛИВО!)
baseurl: "/personal" 
url: "https://phoenixway.github.io"

# Тема та плагіни
remote_theme: pages-themes/hacker@v0.2.0 # Змінено на тему "Hacker"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Налаштування меню (поки що залишаємо, як є)
header_pages:
  - about.md