# Налаштування сайту
title: "Думки та нотатки"
author: "Roman Kozak"
description: "Особистий блог про життя, ідеї та все, що не стосується коду."

# URL та baseurl (ВАЖЛИВО!)
# Замініть "personal-blog" на назву вашого репозиторію
baseurl: "/personal" 
url: "https://phoenixway.github.io"

# Тема та плагіни (ОНОВЛЕНО ТУТ)
remote_theme: jekyll/minima # Використовуємо надійніший метод
plugins:
  - jekyll-remote-theme # Додаємо плагін для роботи remote_theme
  - jekyll-feed
  - jekyll-seo-tag

# Налаштування меню
header_pages:
  - about.md