# Налаштування сайту
title: "PhoenixWay's Explorations"
description: "A collection of my non-technical projects, writings, and explorations."
author: "Roman Kozak"

# URL та baseurl (ВАЖЛИВО!)
baseurl: "/personal" 
url: "https://phoenixway.github.io"

# Тема та плагіни
remote_theme: pages-themes/hacker@v0.2.0 # Змінено на тему "Hacker"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Налаштування меню (поки що залишаємо, як є)
header_pages:
  - about.md
  - creations.md

# Collections for non-technical projects
collections:
  creations:
    output: true
